import Head from "next/head";
import Script from "next/script";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home() {
  const num = 3;
  return (
    <div className={styles.container}>
      <Head>
        <title> Create Next App </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Script src="./sv.js" strategy="lazyOnload"></Script>
       */}
      <nav className={styles.mainNav}>
        <ul>
          <Link href={"/"}>
            <a>
              <li> Home </li>
            </a>
          </Link>
          <Link href={"/about"}>
            <a>
              <li>About</li>
            </a>
          </Link>
          <Link href={"/blog"}>
            <a>
              <li> Blog </li>
            </a>
          </Link>
          <Link href={"/contact"}>
            <a>
              <li> Contact </li>
            </a>
          </Link>
        </ul>
      </nav>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Hunting <a href="#"> Coder </a>
        </h1>
        <p className={styles.description}>
          A blog for hunting coders by a hunting coder
        </p>
        <div className="blogs">
          <h2> Popular Blogs </h2>
          <div>
            <h1>
              How to learn
              <span className={styles.nextjen} href="#">
                NextJS
              </span>
            </h1>
            <p> NextJS is ReactJS Framework </p>
          </div>
          <div>
            <h1>
              How to learn
              <span className={styles.nextjen} href="#">
                NextJS
              </span>
            </h1>
            <p> NextJS is ReactJS Framework </p>
          </div>
          <div>
            <h1>
              How to learn
              <span className={styles.nextjen} href="#">
                NextJS
              </span>
            </h1>
            <p> NextJS is ReactJS Framework </p>
          </div>
          {/* {Array.apply(0, Array(num)).map(function (x, i) {
                                    return (
                                      <>
                                        <h1>
                                          How to learn
                                          <span className={styles.nextjen} href="#">
                                            NextJS
                                          </span>
                                        </h1>
                                        <p>NextJS is ReactJS Framework</p>
                                      </>
                                    );
                                  })} */}
        </div>
      </main>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
