import Head from "next/head";
import Script from "next/script";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Blog.module.css";

export default function Home() {
  // const num = 3;
  return (
    <div className={styles.container}>
      <style jsx>
        {`
          h2 {
            font-size: 38px;
          }
          h3 {
            font-size: 28px;
          }
        `}
      </style>
      <Head>
        <title> Create Next App </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Script src="./sv.js" strategy="lazyOnload"></Script>
       */}
      <main className={styles.main}>
        <h1 className={styles.title}>
          Hero <a href="#"> Hunter </a>
          {/* <span className="mySpan">Hello</span> */}
        </h1>
        <div className={styles.imageWrap}>
          <Image
            className={styles.myImg}
            src="/JFIXMt.png"
            width={400}
            height={200}
          />
        </div>
        <p className={styles.description}>
          A blog for hunting coders by a hunting coder
        </p>
      </main>
    </div>
  );
}
